### ISSUE TITLE
how to reproduce AQD result

### ISSUE THREAD

**Issue by XiaotaoChen** [blueardour/model-quantization#6]
Hi, It's inspiring about the AQD result in detection tasks. However, It seems like there have no relative configurations in `config` directory. Can you tell how to reproduce `AQD`'s result ? Or Is it outside the scope of this open source repo ?

**Comment by blueardour** [comment]
Hi, @XiaotaoChen 

Thanks for your interest on our project. Currently the quantization on classification task is visible to public. For detection task (as well as segmentation and text spotting), we are keeping to improve the performance and aslo the quality of the code. Thus, we temporarily make it invisible until the repo becomes stable.

**Comment by XiaotaoChen** [comment]
Thanks, It's great. And can you tell a detail milestone or roadmap about your following planning? @blueardour

**Comment by blueardour** [comment]
Hi, @XiaotaoChen 

I have long term goal of 
- Employ the model compression (mainly quantization) technologies to various tasks. Currently focusing on computer vision tasks, such as detection/segmentation/super resolution. and later NLP problems. The quantization support for the detection task is expected to finished in eary September.

- Develop acceleration code to obtain runtime benefit of model quantization on real platforms. Currently focusing on embedded devices.

**Comment by XiaotaoChen** [comment]
Thanks for your notifications. @blueardour  Looking forward to seeing your next work.

**Comment by XiaotaoChen** [comment]
Hi,, @blueardour How about the quantization support for the detection task in your roadmap? Looking forward to the open source of your AQD method.

**Comment by blueardour** [comment]
@XiaotaoChen 

Hi, Sorry for not feedback in time. I just enjoyed all the accumulative annual leave for last two years.

All the work about quantization of detection task has been finished. We are preparing and updating the arixv paper recent days.

Besides the detection, we enable quantization support of segmentation, SR, etc. in the same project.  Some of the work are not finished yet. We prefer not to release the quantization code of detection alone. Timeline is still under discussion from all group members.
