### ISSUE TITLE
'BasicBlock' object has no attribute 'shrink'

### ISSUE THREAD

**Issue by HaloTrouvaille** [blueardour/model-quantization#7]
Thank you for your great work! When I run the command 'bash train.sh config/config.xnor.train-strach.dali.bin.resnet18', some errors occured as following AttributeError: 'BasicBlock' object has no attribute 'shrink'
Please help me. Thank you!

**Comment by blueardour** [comment]
Sorry for the issue. The shrink is for some features under development. I missed to clean the code for the release version. It might be OK now.

**Comment by HaloTrouvaille** [comment]
OK, I changed the code. Thank you!
