### ISSUE TITLE
What dose the option 'custom-update' mean?

### ISSUE THREAD

**Issue by liyue2ppy** [blueardour/model-quantization#8]
if 'custom-update' in args.keyword:
            for m in model.modules():
                if hasattr(m, 'update_quantization_parameter'):
                    m.update_quantization_parameter(epoch=epoch, length=length, lr=lr)

**Comment by blueardour** [comment]
In most cases, it only enable the 'update_quantization_parameter' function, which updates some internal hyper-parameters, such as the index, current epoch or fm_bit/half_range. For LQ-net, it also impacts the update strategy of the basis (refer models/quant.py #244). 

If you feel confused, suggestions are welcome to change the behaviour.

**Comment by blueardour** [comment]
Reopen if further question.
