### ISSUE TITLE
检测模型浮点训练，关于FPN-BN,Head-BN的实验

### ISSUE THREAD

**Issue by TangShengqin** [blueardour/model-quantization#9]
作者你好，我在本地实验了retinanet-res18，采用FPN-BN,Head-BN，超参按照论文中来设置，详细如下：
lr_init = 0.01，wd = "1e-04"，bn_eps = "1e-5"，momentum=0.9，SGD，epoch=1x，warm_up_epoch=1。
但是尝试了多次，第一个epoch的某次迭代一直出现Loss崩掉的情况：
LR=0.00226361,  FocalLoss=0.738,  SmoothL1Loss=0.348
LR=0.00229090,  FocalLoss=406204.126,  SmoothL1Loss=0.662
问题：
1、请问作者当时实验的时候有遇到这个情况吗？
2、loss崩掉有什么解决建议吗？

**Comment by blueardour** [comment]
Hi, @TangShengqin 

I didn't meet the problem. Could you share the `log.txt` and config file for me to check if it is the structure issue?

**Comment by blueardour** [comment]
Closed.

Repoen if the issue still exists.
